# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(name: "Home Repairs")
# Category.create(name: "Landscaping")
# Category.create(name: "Gardening")
# Category.create(name: "Furniture")
# Category.create(name: "Event")
# Category.create(name: "Travel")
# Category.create(name: "Transportation")
Category.create(name: "Auto Repair")
# Category.create(name: "Cooking")
# Category.create(name: "Shopping")
# Category.create(name: "Childcare")
Category.create(name: "Pet Care")
# Category.create(name: "Healthcare")
# Category.create(name: "Beauty")
# Category.create(name: "Education")
# Category.create(name: "Fitness")
# Category.create(name: "Entertainment")
# Category.create(name: "Technology")
# Category.create(name: "Design")
# Category.create(name: "Insurance")
# Category.create(name: "Finance")
# Category.create(name: "Business")
# Category.create(name: "Security")
# Category.create(name: "Government")
# Category.create(name: "Non-profit")
# Category.create(name: "Creer Advise")
# Category.create(name: "Coaching")